from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34faa0a0b25a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # CRITICAL FIX 1: Add 'hashed_password' as nullable=True initially. 
    # If the table has existing rows, they must be populated with a hash later.
    op.add_column('clients', sa.Column('hashed_password', sa.String(), nullable=True)) 
    
    # CRITICAL FIX 2: Add 'role' with a server_default. This safely assigns 'client' 
    # to all existing rows before enforcing nullable=False.
    op.add_column('clients', sa.Column('role', sa.String(), server_default='client', nullable=False))
    
    # Drop the old 'password' column
    op.drop_column('clients', 'password')

    # Handle email uniqueness and indexing
    op.drop_constraint(op.f('clients_email_key'), 'clients', type_='unique')
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=True)
    
    # Re-create/ensure foreign key exists (autogenerated)
    op.create_foreign_key(None, 'events', 'clients', ['client_id'], ['id'])
    
    # OPTIONAL NEXT STEP: Manually remove the 'server_default' 
    # after applying the migration to prevent it from auto-populating new rows in the future.
    op.alter_column('clients', 'role', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.add_column('clients', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.create_unique_constraint(op.f('clients_email_key'), 'clients', ['email'])
    op.drop_column('clients', 'role')
    op.drop_column('clients', 'hashed_password')
    # ### end Alembic commands ###